# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161220_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tripparticipant', to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tripuser', to='myapp.User'),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together=set([('user', 'participant')]),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
