# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='planner',
        ),
        migrations.AddField(
            model_name='schedule',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantschedule', to='myapp.User'),
        ),
    ]
